### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.servicefabric.models.TestErrorChaosEvent
  fullName: azure.servicefabric.models.TestErrorChaosEvent
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.serialization.Model
    type: azure.servicefabric.models.chaos_event.ChaosEvent
  langs:
  - python
  module: azure.servicefabric.models
  name: TestErrorChaosEvent
  source:
    id: TestErrorChaosEvent
    path: azure-servicefabric\azure\servicefabric\models\test_error_chaos_event.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\test_error_chaos_event.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'Describes a Chaos event that gets generated when an unexpected event occurs

    in the Chaos engine.

    For example, due to the cluster snapshot being inconsistent, while faulting

    a faultable entity, Chaos found that the entity was alreay faulted -- which

    would be an unexpected event.

    .

    '
  syntax:
    content: TestErrorChaosEvent(time_stamp_utc, reason=None)
    parameters:
    - description: ''
      id: time_stamp_utc
      type:
      - datetime
    - description: 'Polymorphic Discriminator

        '
      id: kind
      type:
      - str
    - description: ''
      id: reason
      type:
      - str
  type: class
  uid: azure.servicefabric.models.TestErrorChaosEvent
references: []
